apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: smart-farm-backend:v1
        ports:
        - containerPort: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000